spring:
  application:
    name: order_service

  datasource:
    url: jdbc:postgresql://localhost:5432/orderservice?autoreconnect=true&createDatabaseIfNotExist=true&characterEncoding=utf8
    username: ordersUser
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080